/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/xFIctChx8Ec
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Separator } from "@/components/ui/separator"

export function signin() {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 overflow-auto bg-black bg-opacity-50 dark:bg-white/50">
      <div className="flex flex-col w-full max-w-sm overflow-hidden bg-white rounded-xl shadow-2xl dark:bg-gray-950">
        <div className="p-6 space-y-4">
          <div className="space-y-2 text-center">
            <h2 className="text-2xl font-bold">Sign in to your account</h2>
            <p className="text-gray-500 dark:text-gray-400">Enter your information to access your account</p>
          </div>
          <div className="space-y-2">
            <Label className="text-sm" htmlFor="email">
              Email
            </Label>
            <Input id="email" placeholder="m@example.com" type="email" />
          </div>
          <div className="space-y-2">
            <Label className="text-sm" htmlFor="password">
              Password
            </Label>
            <Input id="password" type="password" />
          </div>
          <Button className="w-full">Sign in</Button>
        </div>
        <Separator />
        <div className="p-4">
          <Button className="w-full" variant="outline">
            Sign in with Google
          </Button>
        </div>
      </div>
    </div>
  )
}
